# Generated by Django 6.0.3 on 2026-05-03 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '已拉黑的AccessToken',
                'verbose_name_plural': '已拉黑的AccessToken',
                'db_table': 'users_blacklisted_access_token',
            },
        ),
    ]
