# Generated by Django 6.0.3 on 2026-05-03 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='是否已拉黑')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_token_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AccessToken记录',
                'verbose_name_plural': 'AccessToken记录',
                'db_table': 'users_access_token_record',
            },
        ),
        migrations.DeleteModel(
            name='BlacklistedAccessToken',
        ),
    ]
